sudo: required
services:
  - docker
os:
  - linux
  - osx
language: minimal
env:
  - PY="2.7"
  - PY="3.4"
  - PY="3.5"
  - PY="3.6"
before_install:
  - ./.ci/wheels.sh
install:
  - "[ -f __wheels.txt ] && ./.ci/wheels-install.sh"
script:
  - "[ -f __wheels.txt ] && ./.ci/wheels-build.sh"
deploy:
  - '[ -f __wheels.txt -a "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" -a -n "$encrypted_632cb16dd578_key" ] && ./.ci/wheels-deploy.sh'
