sudo: required
services:
  - docker
os:
  - linux
  - osx
language: minimal
env:
  - PY="2.7"
  - PY="3.4"
  - PY="3.5"
  - PY="3.6"
  - PY="3.7"
before_install:
  - ./.ci/wheels.sh
install:
  - |
    if [ -f __wheels.txt ]; then
        ./.ci/wheels-install.sh
    else
        echo "install: nothing to do"
    fi
script:
  - |
    if [ -f __wheels.txt ]; then
        ./.ci/wheels-build.sh
    else
        echo "build: nothing to do"
    fi
after_success:
  - |
    if [ -f __wheels.txt -a "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" -a -n "$encrypted_632cb16dd578_key" ]; then
        ./.ci/wheels-deploy.sh
    else
        echo "deploy: nothing to do"
    fi
