---
# rdflib-jsonld uses the `use_2to3=True` option of `setup()`, for which Setuptools has
# removed support in v58.0.0
name: rdflib-jsonld
version: 0.5.0
type: wheel
purepy: true
prebuild:
  # Upstream bug: since it uses use_2to3 it cannot be universal
  wheel: sed -i -e 's/^universal = 1/universal = 0/' "${SRC_ROOT}"/setup.cfg
