---

name: uWSGI
version: 2.0.17.1
type: wheel
imageset: cext-py2-wheel
purepy: false
prebuild:
  all: cp "${SRC_ROOT_0}"/setup.cpyext.py "${SRC_ROOT_0}"/setup.py
  wheel: >
    [ $(uname -s) != 'Darwin' ] ||
    curl https://github.com/natefoo/uwsgi/commit/24c49361613fa3dbd0b61eb1a97733d48c00ff39.patch |
    patch -d "${SRC_ROOT_0}" -p1
apt:
  - libpcre2-dev
yum:
  - pcre-devel
brew:
  - pcre
skip_tests:
  - uwsgidecorators
